CREATE TABLE EMPRESA(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOMEFANTASIA	NVARCHAR(150)		NOT NULL,
	RAZAOSOCIAL		NVARCHAR(150)		NOT NULL,
	CNPJ			NVARCHAR(14)		NOT NULL,
	PRIMARY KEY(ID))
GO

CREATE TABLE FUNCIONARIO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	CPF				NVARCHAR(11)		NOT NULL,
	MATRICULA		NVARCHAR(8)			NOT NULL,
	DATAADMISSAO	DATE				NOT NULL,
	STATUS			INTEGER				NOT NULL,
	IDEMPRESA		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDEMPRESA) REFERENCES EMPRESA(ID))
GO